name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_id: ${{ steps.create-release.outputs.id }}

    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Image Tiler ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-and-upload:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: windows-latest
            target: windows
            ext: .msi
          - name: macos-latest
            target: macos
            ext: .dmg
          - name: ubuntu-latest
            target: linux
            ext: _amd64.deb

    runs-on: ${{ matrix.platform.name }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform.name == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install app dependencies
        run: bun install

      - name: Build the app
        run: bun run tauri:build
          
      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/${{ matrix.platform.target }}/${{ matrix.platform.target == 'linux' && 'deb' || matrix.platform.target }}/*${{ matrix.platform.ext }}
          asset_name: image-tiler-${{ github.ref_name }}-${{ matrix.platform.target }}${{ matrix.platform.ext }}
          asset_content_type: application/octet-stream